### ISSUE TITLE
Article

### ISSUE THREAD

**Issue by niubifuwei** [lenalee103/Aggregates-Database-based-on-ACGAN#1]
Hello, has your article been published?
Can you send me the name?

**Comment by lenalee103** [comment]
I'm sorry I can't. The paper is under reviewed. 



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            feifei li
                            
                            
                                
                                    邮箱：feifei2009li@gmail.com
                                
                        
                    
                
            
        
    


On 11/24/2020 08:26, niubifuwei wrote: 
Hello, has your article been published?
Can you send me the name?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/lenalee103/Aggregates-Database-based-on-ACGAN/issues/1",
"url": "https://github.com/lenalee103/Aggregates-Database-based-on-ACGAN/issues/1",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
